spring:
  application:
    name: users-service

  datasource:
    url: jdbc:postgresql://localhost:5432/movieticketsdb
    username: moviedb
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

security:
  jwt:
    secret: 3f8a2b1c9d4e7f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a
    expiration: 86400000